### ISSUE TITLE
Update resource path name

### ISSUE THREAD

**Issue by bytefire** [electricimp/ElectricImp-Sublime#20]
Hi,

Should resource path name point to `ElectricImp-Sublime` instead of `imp-developer`? This patch fixed the resource not found error on my side when creating project:

[fix_resource_path.txt](https://github.com/electricimp/ElectricImp-Sublime/files/1159247/fix_resource_path.txt)

Thanks

**Comment by ppetrosh** [comment]
Hi @bytefire,

How do you install the plugin? Which platform is it? Can you please provide the full Sublime Text 3 log with the error (use `ctrl`+` to switch to the console).

Thanks,
Pavel

**Comment by bytefire** [comment]
Hi,

I git cloned the repo into ~/.config/sublime-text3/Plugins/ directory. This is on Linux. Everything was fine except this. 

Cheers

**Comment by ppetrosh** [comment]
Thanks for the details. At first glance I would say it's a documentation issue. But let me see if I can address it in the code to make installation path agnostic.

**Comment by ppetrosh** [comment]
@bytefire, it should have been fixed now. Can you please try installing the plugin via the Package Control? Thanks!

**Comment by bytefire** [comment]
Will give it a try over the weekend if that's alright? Litte tight with time rn.

Thanks

**Comment by ppetrosh** [comment]
@bytefire absolutely! Thank you.

**Comment by ppetrosh** [comment]
@bytefire closing as fixed. please reopen if that's still an issue.
