### ISSUE TITLE
Support for impCentral OTP

### ISSUE THREAD

**Issue by ppetrosh** [electricimp/ElectricImp-Sublime#53]
Two-Factor Auth flow should be supported in the Sublime Text Plugin https://apidoc.electricimp.com/#tag/Auth

A new step when authenticating during the project creation should be added if OTP is enabled.

**Comment by thomaskoehn-kisi** [comment]
@ppetrosh Having the same problem right now during normal login with the Sublime plugin. It says that TOTP is required, but it does not give me an option to enter it. When will this be added?

**Comment by ppetrosh** [comment]
Yeah, that's not implemented yet. We'll prioritize this work appropriately. I'm sorry for the inconvenience.

**Comment by ppetrosh** [comment]
Fixed in v2.1.0
